spring:
  cloud:
    gateway:
      routes:
        - id: user-route
          uri: lb://service-user
          predicates:
            - Path=/api/user/**
        - id: lab-route
          uri: lb://service-lab
          predicates:
            - Path=/api/lab/**
        - id: reservation-route
          uri: lb://service-reservation
          predicates:
            - Path=/api/reservation/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: "http://localhost:5173"
            allowed-headers: '*'
            allowed-methods:
              - '*'