spring:
  application:
    name: service-user
  datasource:
    url: jdbc:mysql://localhost:3306/lab_user_db?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: hao@0829
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        import-check:
          enabled: false
server:
  port: 8000

mybatis:
  mapper-locations: classpath:mapper/*.xml
hao:
  jwt:
    user-secret-key: xQ7bZp2KtFg9DsA3JhLc5Rv8WyEu1Mo4S
    user-ttl: 7200000
    user-token-name: token
