spring:
  application:
    name: service-lab
  datasource:
    url: jdbc:mysql://localhost:3306/lab_lab_db?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: hao@0829
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        import-check:
          enabled: false
  profiles:
    include: feign
server:
  port: 9000

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl