spring:
  application:
    name: service-lab
  datasource:
    url: jdbc:mysql://localhost:3306/lab_lab_db?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: hao@0829
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        import-check:
          enabled: false
  profiles:
    include: feign
  data:
    redis:
      database: 6
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    virtual-host: /hao
    username: hao
    password: hao@0829
server:
  port: 9000


mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
