spring:
  cloud:
    openfeign:
      client:
        config:
          default:
            logger-level: full
            connect-timeout: 3000
            read-timeout: 5000
          service-reservation:
            logger-level: full
            connect-timeout: 3000
            read-timeout: 5000